// SPDX-License-Identifier: MIT

pragma solidity ^0.8.2;

import "@openzeppelin/contracts-upgradeable/token/ERC721/ERC721Upgradeable.sol";
import "@openzeppelin/contracts-upgradeable/token/ERC721/extensions/ERC721EnumerableUpgradeable.sol";
import "@openzeppelin/contracts-upgradeable/token/ERC721/extensions/ERC721BurnableUpgradeable.sol";
import "@openzeppelin/contracts-upgradeable/token/ERC721/extensions/ERC721PausableUpgradeable.sol";
import "@openzeppelin/contracts-upgradeable/access/AccessControlEnumerableUpgradeable.sol";
import "@openzeppelin/contracts-upgradeable/utils/ContextUpgradeable.sol";
import "@openzeppelin/contracts-upgradeable/utils/CountersUpgradeable.sol";
import "@openzeppelin/contracts-upgradeable/proxy/utils/Initializable.sol";

/**
 * @dev {ERC721} token, including:
 *
 *  - ability for holders to burn (destroy) their tokens
 *  - a minter role that allows for token minting (creation)
 *  - a pauser role that allows to stop all token transfers
 *  - token ID and URI autogeneration
 *
 * This contract uses {AccessControl} to lock permissioned functions using the
 * different roles - head to its documentation for details.
 *
 * The account that deploys the contract will be granted the minter and pauser
 * roles, as well as the default admin role, which will let it grant both minter
 * and pauser roles to other accounts.
 */
contract SingleTokenWithType is 
    Initializable, 
    ContextUpgradeable, 
    AccessControlEnumerableUpgradeable, 
    ERC721EnumerableUpgradeable, 
    ERC721BurnableUpgradeable, 
    ERC721PausableUpgradeable
    {
    using CountersUpgradeable for CountersUpgradeable.Counter;

    bytes32 public constant MINTER_ROLE = keccak256("MINTER_ROLE");
    bytes32 public constant PAUSER_ROLE = keccak256("PAUSER_ROLE");

    string private _baseTokenURI;

    // Mapping  from interface to state
    mapping (string => bool) private _interfaces;
    // type list
    uint256[] private _typeList;
    // Mapping  from type to exists(false: no true: yes)
    mapping (uint256 => bool) private _typeExists;
    // Mapping  from type to locked(false: no true: yes)
    mapping (uint256 => bool) private _typeLocked;
    // Mapping  from type to capacity
    mapping (uint256 => uint256) private _typeCapacity;
    // Mapping  from type to counter
    mapping (uint256 => CountersUpgradeable.Counter) private _typeCounter;
    // Mapping  from type to datas
    mapping (uint256 => string) private _typeDatas;
    // Mapping  from token to type
    mapping (uint256 => uint256) private _typeOfToken;


    function initialize(string memory name, string memory symbol, string memory baseTokenURI) public virtual initializer {
        __SingleTokenWithType_init(name, symbol, baseTokenURI);
    }
    /**
     * @dev Grants `DEFAULT_ADMIN_ROLE`, `MINTER_ROLE` and `PAUSER_ROLE` to the
     * account that deploys the contract.
     *
     * Token URIs will be autogenerated based on `baseURI` and their token IDs.
     * See {ERC721-tokenURI}.
     */
    function __SingleTokenWithType_init(string memory name, string memory symbol, string memory baseTokenURI) internal initializer {
        __Context_init_unchained();
        __ERC165_init_unchained();
        __AccessControl_init_unchained();
        __AccessControlEnumerable_init_unchained();
        __ERC721_init_unchained(name, symbol);
        __ERC721Enumerable_init_unchained();
        __ERC721Burnable_init_unchained();
        __Pausable_init_unchained();
        __ERC721Pausable_init_unchained();
        __SingleTokenWithType_init_unchained(baseTokenURI);
    }

    function __SingleTokenWithType_init_unchained(string memory baseTokenURI) internal initializer {
        _baseTokenURI = baseTokenURI;

        _setupRole(DEFAULT_ADMIN_ROLE, _msgSender());
        _setupRole(MINTER_ROLE, _msgSender());
        _setupRole(PAUSER_ROLE, _msgSender());
        _tokenManager = _msgSender();
    }

    function _baseURI() internal view virtual override returns (string memory) {
        return _baseTokenURI;
    }

    /**
     * @dev Creates a new token for `to`. Its token ID will be automatically
     * assigned (and available on the emitted {IERC721-Transfer} event), and the token
     * URI autogenerated based on the base URI passed at construction.
     *
     * See {ERC721-_mint}.
     *
     * Requirements:
     *
     * - the caller must have the `MINTER_ROLE`.
     */
    function mint(address to, uint256 tokenId, uint256 typeId) public virtual {
        require(hasRole(MINTER_ROLE, _msgSender()), "SingleTokenWithType: must have minter role to mint");

        // We cannot just use balanceOf to create the new tokenId because tokens
        // can be burned (destroyed), so we need a separate counter.
        _safeMint(to, tokenId);

        _afterMint(tokenId, typeId);
    }

    /**
     * @dev Pauses all token transfers.
     *
     * See {ERC721Pausable} and {Pausable-_pause}.
     *
     * Requirements:
     *
     * - the caller must have the `PAUSER_ROLE`.
     */
    function pause() public virtual {
        require(hasRole(PAUSER_ROLE, _msgSender()), "SingleTokenWithType: must have pauser role to pause");
        _pause();
    }

    /**
     * @dev Unpauses all token transfers.
     *
     * See {ERC721Pausable} and {Pausable-_unpause}.
     *
     * Requirements:
     *
     * - the caller must have the `PAUSER_ROLE`.
     */
    function unpause() public virtual {
        require(hasRole(PAUSER_ROLE, _msgSender()), "SingleTokenWithType: must have pauser role to unpause");
        _unpause();
    }

    /**
     * @dev See {IERC165-supportsInterface}.
     */
    function supportsInterface(bytes4 interfaceId) public view virtual override(AccessControlEnumerableUpgradeable, ERC721Upgradeable, ERC721EnumerableUpgradeable) returns (bool) {
        return super.supportsInterface(interfaceId);
    }


    /**
     * @dev append token type
     *
     * Requirements:
     *
     * - the caller must have the `DEFAULT_ADMIN_ROLE`.
     */
    function appendType(uint256 typeId, uint256 capacity, string calldata datas) public virtual {
        require(hasRole(DEFAULT_ADMIN_ROLE, _msgSender()), "SingleTokenWithType: must have admin role to grant");
        require(!_typeExists[typeId], "type already exists.");
        require(!paused(), "SingleTokenWithType: token transfer while paused");

        _typeExists[typeId] = true;
        _typeLocked[typeId] = false;
        _typeDatas[typeId]  = datas;
        _typeList.push(typeId);

        _typeCapacity[typeId] = capacity;
    }


    /**
     * @dev incremen token type capacity
     *
     * Requirements:
     *
     * - the caller must have the `DEFAULT_ADMIN_ROLE`.
     */
    function incrementTypeCapacity(uint256 typeId, uint256 count) public virtual {
        require(hasRole(DEFAULT_ADMIN_ROLE, _msgSender()), "SingleTokenWithType: must have admin role to grant");
        require(_typeExists[typeId], "type does not exists.");
        require(!paused(), "SingleTokenWithType: token transfer while paused");

        uint256 current_capacity = _typeCapacity[typeId];
        require(current_capacity + count <= type(uint256).max, "value overflow.");


        _typeCapacity[typeId] = current_capacity + count;
    }

    /**
     * @dev get token type
     */
    function indexStart() public view virtual returns (uint256) {
        return 0;
    }
    /**
     * @dev get token type
     */
    function typeByIndex(uint256 index) public view virtual returns (uint256) {
        return _typeList[index];
    }

    /**
     * @dev get token type
     */
    function typeDatasOfType(uint256 typeId) public view virtual returns (string memory) {
        require(_typeExists[typeId], "typeId does not exists");
        return _typeDatas[typeId];
    }
    /**
     * @dev get token type
     */
    function typeOfToken(uint256 tokenId) public view virtual returns (uint256) {
        return _typeOfToken[tokenId];
    }

    /**
     * @dev get type count
     */
    function countOfType() public view virtual returns (uint256) {
        return _typeList.length;
    }


    /**
     * @dev check type is exists? 
     */
    function typeIsExists(uint256 typeId) public view virtual returns (bool) {
        return _typeExists[typeId];
    }

    /**
     * @dev check type is locked? 
     */
    function typeIsLocked(uint256 typeId) public view virtual returns (bool) {
        return _typeLocked[typeId];
    }
    /**
      * @dev token manager 
    */
    function tokenManager() public view virtual returns(address) {
        return _tokenManager;
    }


     /** @dev lock type ? 
     *
     * Requirements:
     *
     * - the caller must have the `DEFAULT_ADMIN_ROLE`.
     */
    function lockType(uint256 typeId) public virtual {
        require(hasRole(DEFAULT_ADMIN_ROLE, _msgSender()), "SingleTokenWithType: must have admin role to grant");
        _typeLocked[typeId] = true;
    }

    /**
     * @dev unlock type ? 
     *
     * Requirements:
     *
     * - the caller must have the `DEFAULT_ADMIN_ROLE`.
     */
    function unlockType(uint256 typeId) public virtual {
        require(hasRole(DEFAULT_ADMIN_ROLE, _msgSender()), "SingleTokenWithType: must have admin role to grant");
        _typeLocked[typeId] = false;
    }

    /**
     * @dev updateManager
     *
     * Requirements:
     *
     * - the caller must have the `DEFAULT_ADMIN_ROLE`.
     */
    function updateTokenManager(address manager) public virtual {
        require(hasRole(DEFAULT_ADMIN_ROLE, _msgSender()), "SingleTokenWithType: must have admin role to grant");
        require(!paused(), "SingleTokenWithType: token transfer while paused");
        require(_tokenManager != manager, "SingleTokenWithType: this manager already exists.");

        _tokenManager = manager;
    }

/***************************************************************************************************
*                  internal functions                           
***************************************************************************************************/

    function _beforeTokenTransfer(address from, address to, uint256 tokenId, uint256 batchSize) internal virtual override(ERC721Upgradeable, ERC721EnumerableUpgradeable, ERC721PausableUpgradeable) {
        super._beforeTokenTransfer(from, to, tokenId, batchSize);
    }

    function _burn(uint256 tokenId) 
    internal 
    virtual 
    override 
    {
        super._burn(tokenId);
        _typeOfToken[tokenId] = 0;
    }

    function _afterMint(uint256 tokenId, uint256 typeId)
    internal
    virtual
    {
        require(_typeExists[typeId], "typeId does not exists");
        require(!_typeLocked[typeId], "typeId is locked");
        require(_typeCounter[typeId].current() < _typeCapacity[typeId], "type is max capacity");

        _typeOfToken[tokenId] = typeId;
        _typeCounter[typeId].increment();

        _approve(_tokenManager, tokenId);
    }

    function _checkInterface(string memory api)
    internal
    virtual
    {
        require(_interfaces[api], "interface is closed.");
    }

    function _SetInterface(string memory api, bool state)
    internal
    virtual
    {
        _interfaces[api] = state;
    }

    /**
     * @dev Approve `to` to operate on `tokenId`
     *
     * use to if _tokenManager is 0x0
     * use _tokenManager if _tokenManager is't 0x0
     * Emits a {Approval} event.
     */
    function _approve(address to, uint256 tokenId) internal virtual override{
        // set to address as approve address to when to != address(0)
        // other set _tokenmanager as approve address
        if (to != address(0)) {
            super._approve(to, tokenId);
        } else {
            super._approve(_tokenManager, tokenId);
        }
    }

    uint256[48] private __gap;
    address private _tokenManager;
}
